# Generated by Django 5.1.2 on 2024-10-26 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_rename_phone_no_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='website',
        ),
    ]
