# Generated by Django 5.1.2 on 2024-10-27 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_remove_company_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='cv',
        ),
    ]
