# Generated by Django 5.1.2 on 2024-10-27 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('workplace_type', models.CharField(choices=[('Remote', 'Remote'), ('Office', 'Office'), ('Hybrid', 'Hybrid')], max_length=50)),
                ('salary', models.CharField(max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('posted_date', models.DateField()),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship')], max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('job_category', models.CharField(blank=True, choices=[('Automotive-Jobs', 'Automotive-Jobs'), ('HealthCare', 'HealthCare'), ('Customer-Service', 'Customer-Service'), ('Project-Management', 'Project-Management'), ('Development', 'Development'), ('Design', 'Design'), ('Marketing', 'Marketing'), ('Accounting-Finance', 'Accounting-Finance')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField()),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(limit_choices_to={'is_employee': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobapp.job')),
            ],
        ),
    ]
